-- Run once in Supabase → SQL Editor

create table if not exists public.items (
  id         bigint generated by default as identity primary key,
  title      text not null,
  done       boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.items enable row level security;

-- Allow API access via anon/service keys (demo app)
create policy "allow all on items"
  on public.items for all
  using (true)
  with check (true);
